#!/bin/bash

# Muestra el menu general
_menu()
{
  echo
  echo -e "\e[36mUTILS Pro-Expert 1.0.0\e[0m"
  echo
  echo -e "\e[32mAsegurate de estar en el directorio de trabajo deseado\e[0m"
  echo -e "\e[32mEl directorio de trabajo actual es:\e[0m"
  echo ""
  pwd
  echo ""
  echo "Menú de opciones:"
  echo
  echo " 1) Cambiar dueño:grupo (juanjo:www-data)"
  echo " 2) Abrir directorios"
  echo " 3) Cerrar directorios"
  echo " 4) Abrir archivos"
  echo " 5) Cerrar archivos"
  echo " 6) Ver archivos antiguos"
  echo " 7) Borrar archivos antiguos"
  echo " 8) Ver espacio usado"
  echo " 9) Buscar archivos mas grandes"
  echo
  echo " 0) Salir"
  echo -e "\e[32m"
  echo -n "Indica una opción: "
}

while :
do
  case $opc in
    1)
        clear
        echo -e "\e[36mCambiando dueño:grupo a directorios...\e[0m"
        find ./ -type d | while read var1; do sudo chown juanjo:www-data "$var1"; done
        echo -e "\e[36mCambiando dueño:grupo a archivos...\e[0m"
        find ./ -type f | while read var1; do sudo chown juanjo:www-data "$var1"; done
        echo -e "\e[36mDirectorios y archivos cambiados\e[0m"
        _menu
        ;;
    2)
      clear
      echo -e "\e[36mAbriendo directorios...\e[0m"
      find ./ -type d | while read var1; do chmod 775 "$var1"; done
      echo -e "\e[36mDirectorios abiertos\e[0m"
      _menu
      ;;

    3)
      clear
      echo -e "\e[36mCerrando directorios...\e[0m"
      find ./ -type d | while read var1; do chmod 555 "$var1"; done
      echo -e "\e[36mDirectorios cerrados\e[0m"
      _menu
      ;;

    4)
      clear
      echo -e "\e[36mAbriendo archivos...\e[0m"
      find ./ -type f | while read var1; do chmod 664 "$var1"; done
      echo -e "\e[36mArchivos abiertos\e[0m"
      _menu
      ;;

    5)
      clear
      echo -e "\e[36mCerrando archivos...\e[0m"
      find ./ -type f | while read var1; do chmod 4444 "$var1"; done
      echo -e "\e[36mArchivos abiertos\e[0m"
      _menu
      ;;

    6)
      clear
      echo -e "\e[36mListando archivos antiguos...\e[0m"
      find ./ -type f -mtime +365
      _menu
      ;;

    7)
      clear
      echo -e "\e[36mBorrando archivos antiguos...\e[0m"
      find ./ -type f -mtime +365 -delete
      echo -e "\e[36mArchivos borrados\e[0m"
      _menu
      ;;

    8)
      clear
      echo -e "\e[36mMostrando espacio usado...\e[0m"
      sudo du -shc
      _menu
      ;;

    9)
      clear
      echo -e "\e[36mMostrando archivos mas grandes...\e[0m"
      sudo du -aBm ./ 2>/dev/null | sort -nr | head -n 10
      _menu
      ;;

    0)
      echo -e "\e[36mHasta luego $USER\e[0m"
      exit
      ;;

    *) # Esta opcion se ejecuta si no es ninguna de las anteriores
      clear
      _menu
      ;;
  esac

read opc

done