#!/bin/bash

# Muestra el menu general
_menu()
{
  echo
  echo -e "\e[36mUTILS Pro-Expert 1.0.0\e[0m"
  echo
  echo -e "\e[32mAsegurate de estar en el directorio de trabajo deseado\e[0m"
  echo -e "\e[32mEl directorio de trabajo actual es:\e[0m"
  echo ""
  pwd
  echo ""
  echo "Menú de opciones:"
  echo
  echo " 1) Cambiar dueño:grupo (tienda:tienda)"
  echo " 2) Abrir directorios"
  echo " 3) Cerrar directorios"
  echo " 4) Abrir archivos"
  echo " 5) Cerrar archivos"
  echo " 6) Ver archivos antiguos"
  echo " 7) Borrar archivos antiguos"
  echo " 8) Ver espacio usado"
  echo " 9) Buscar archivos mas grandes"
  echo "10) Ver uso php-cgi"
  echo "11) Ver conexiones web"
  echo "12) Buscar cosas raras en access_log"
  echo "13) Buscar bots en access_log"
  echo
  echo " 0) Salir"
  echo -e "\e[32m"
  echo -n "Indica una opción: "
}

while :
do
  case $opc in
    1)
        clear
        echo -e "\e[36mCambiando dueño:grupo a directorios...\e[0m"
        find ./ -type d | while read var1; do sudo chown tienda:tienda "$var1"; done
        echo -e "\e[36mCambiando dueño:grupo a archivos...\e[0m"
        find ./ -type f | while read var1; do sudo chown tienda:tienda "$var1"; done
        echo -e "\e[36mDirectorios y archivos cambiados\e[0m"
        _menu
        ;;
    2)
      clear
      echo -e "\e[36mAbriendo directorios...\e[0m"
      find ./ -type d | while read var1; do chmod 775 "$var1"; done
      echo -e "\e[36mDirectorios abiertos\e[0m"
      _menu
      ;;

    3)
      clear
      echo -e "\e[36mCerrando directorios...\e[0m"
      find ./ -type d | while read var1; do chmod 555 "$var1"; done
      echo -e "\e[36mDirectorios cerrados\e[0m"
      _menu
      ;;

    4)
      clear
      echo -e "\e[36mAbriendo archivos...\e[0m"
      find ./ -type f | while read var1; do chmod 664 "$var1"; done
      echo -e "\e[36mArchivos abiertos\e[0m"
      _menu
      ;;

    5)
      clear
      echo -e "\e[36mCerrando archivos...\e[0m"
      find ./ -type f | while read var1; do chmod 4444 "$var1"; done
      echo -e "\e[36mArchivos abiertos\e[0m"
      _menu
      ;;

    6)
      clear
      echo -e "\e[36mListando archivos antiguos...\e[0m"
      find ./ -type f -mtime +365
      _menu
      ;;

    7)
      clear
      echo -e "\e[36mBorrando archivos antiguos...\e[0m"
      find ./ -type f -mtime +365 -delete
      echo -e "\e[36mArchivos borrados\e[0m"
      _menu
      ;;

    8)
      clear
      echo -e "\e[36mMostrando espacio usado...\e[0m"
      sudo du -shc
      _menu
      ;;

    9)
      clear
      echo -e "\e[36mMostrando archivos mas grandes...\e[0m"
      sudo du -aBm ./ 2>/dev/null | sort -nr | head -n 10
      _menu
      ;;
    10)
      clear
      echo -e "\e[36mVisualizando uso php-cgi...\e[0m"
      ps aux | grep php-cgi
      _menu
     ;;
    11)
      clear
      echo -e "\e[36mMostrando conexiones web...\e[0m"
      netstat -putona |grep ':80'
      _menu
      ;;
    12)
      clear
      echo -e "\e[36mMostrando cosas raras en access_log...\e[0m"
      awk -F\" '$2 ~ /(SELECT|UNION|INSERT|UPDATE|DELETE)/ {print $1}' /home/tienda/logs/access_log | sort | uniq -c | sort -nr
      _menu
       ;;
    13)
      clear
      echo -e "\e[36mMostrando cosas raras en access_log...\e[0m"
      awk -F\" '{print $6}' /home/tienda/logs/access_log | sort | uniq -c | sort -k1nr | awk '!($1="")' | sed -n 1,500p > /home/tienda/logs/user-agents.txt
      _menu
      ;;

    0)
      echo -e "\e[36mHasta luego $USER\e[0m"
      exit
      ;;

    *) # Esta opcion se ejecuta si no es ninguna de las anteriores
      clear
      _menu
      ;;
  esac

read opc

done
